"""schema inicial

Revision ID: 6bf225eb2dbb
Revises: 
Create Date: 2026-09-12 13:57:54.686680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bf225eb2dbb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organizacao_id', sa.String(), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('jogador_id', sa.String(), nullable=False),
    sa.Column('jogador_nome', sa.String(), nullable=True),
    sa.Column('estrelas', sa.Float(), nullable=True),
    sa.Column('sexo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config',
    sa.Column('organizacao_id', sa.String(), nullable=False),
    sa.Column('estrelas_visiveis', sa.Boolean(), nullable=True),
    sa.Column('checkin_data_aberta', sa.String(), nullable=True),
    sa.Column('checkin_travado', sa.Boolean(), nullable=True),
    sa.Column('contador_acessos', sa.Integer(), nullable=True),
    sa.Column('dias_para_rip', sa.Integer(), nullable=True),
    sa.Column('dias_para_aposentado', sa.Integer(), nullable=True),
    sa.Column('nome_grupo', sa.String(), nullable=True),
    sa.Column('subtitulo', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('cor_primaria', sa.String(), nullable=True),
    sa.Column('cor_secundaria', sa.String(), nullable=True),
    sa.Column('link_rede_social', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('organizacao_id')
    )
    op.create_table('jogadores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organizacao_id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('apelido', sa.String(), nullable=True),
    sa.Column('foto', sa.String(), nullable=True),
    sa.Column('estrelas', sa.Float(), nullable=True),
    sa.Column('sexo', sa.String(), nullable=True),
    sa.Column('porte', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rodadas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organizacao_id', sa.String(), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('rascunho', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rodada_times',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rodada_id', sa.String(), nullable=False),
    sa.Column('time_index', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('player_ids', sa.JSON(), nullable=True),
    sa.Column('vitorias', sa.Integer(), nullable=True),
    sa.Column('vencedor', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['rodada_id'], ['rodadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rodada_times')
    op.drop_table('rodadas')
    op.drop_table('jogadores')
    op.drop_table('config')
    op.drop_table('checkins')
    # ### end Alembic commands ###
