"""organizacoes e usuarios

Revision ID: f634a366df34
Revises: 6bf225eb2dbb
Create Date: 2026-09-12 18:26:40.565687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f634a366df34'
down_revision: Union[str, Sequence[str], None] = '6bf225eb2dbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizacoes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('subtitulo', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('cor_primaria', sa.String(), nullable=True),
    sa.Column('cor_secundaria', sa.String(), nullable=True),
    sa.Column('link_rede_social', sa.String(), nullable=True),
    sa.Column('plano', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('organizacao_id', sa.String(), nullable=True),
    sa.Column('clerk_user_id', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('config') as batch_op:
        batch_op.create_foreign_key('fk_config_organizacao_id', 'organizacoes', ['organizacao_id'], ['id'])
        batch_op.drop_column('nome_grupo')
        batch_op.drop_column('link_rede_social')
        batch_op.drop_column('cor_primaria')
        batch_op.drop_column('cor_secundaria')
        batch_op.drop_column('subtitulo')
        batch_op.drop_column('logo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config') as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('subtitulo', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('cor_secundaria', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('cor_primaria', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('link_rede_social', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('nome_grupo', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint('fk_config_organizacao_id', type_='foreignkey')
    op.drop_table('usuarios')
    op.drop_table('organizacoes')
    # ### end Alembic commands ###
